In [48]:
import tensorflow as tf
import numpy as np
import pandas as pd
from nltk.corpus import stopwords

In [49]:
df = pd.read_csv('cleaned_twitter.csv')
df.head()

sentimen                                              Tweet
0       0.0  barusan liat tulisan di belakang truk rela inj...
1       0.0  her itu lho miss kevin sama keven rebutan gimb...
2       0.0     iya rep gatau saya masih kelas sd ehh di block
3       0.0     saya mohon tepatilah janjimu penantiancintaeps
4       0.0  bukan beria nk kahwin sbb gatal celah kangkang...

In [50]:
# Checking for null values
df.isna().sum()

sentimen      0
Tweet       300
dtype: int64

In [51]:
# Import Module
from sklearn.impute import SimpleImputer

# Pembuatan Imputation dengan pengganti modus
impute_modes = SimpleImputer(strategy='most_frequent')

df['Tweet'] = impute_modes.fit_transform(df[['Tweet']])

In [52]:
# Checking for null values
df.isna().sum()

sentimen    0
Tweet       0
dtype: int64

In [53]:
tweets = df['Tweet']
tweets.head()

0    barusan liat tulisan di belakang truk rela inj...
1    her itu lho miss kevin sama keven rebutan gimb...
2       iya rep gatau saya masih kelas sd ehh di block
3       saya mohon tepatilah janjimu penantiancintaeps
4    bukan beria nk kahwin sbb gatal celah kangkang...
Name: Tweet, dtype: object

In [54]:
max_len = 0
max_words = ''
unique_words = set()
for tweet in tweets.str.split():
    if not tweet:
        continue
    tweet_max = max(tweet, key=len)
    unique_words.update(tweet)
    if max_len < len(tweet_max):
        max_len = len(tweet_max)
        max_words = tweet_max

print(f"{max_len=}\n{max_words=}\n{len(unique_words)=}")

max_len=39
max_words='sejukatgasnusantaraatgasnusantarakaltim'
len(unique_words)=23846


In [55]:
stopwords_list = stopwords.words('indonesian')

# convert list to dictionary
list_stopwords = set(stopwords_list)
list_stopwords

{'ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut'

In [56]:
#remove stopword pada list token
def stopwords_removal(words):
    # word_list = []
    # for word in words.split():
    #     if word not in list_stopwords:
    #         word_list.extend(list(word))
    #         word_list.append(' ')
    # if word_list:
    #     word_list.pop()
    # return word_list
    return ''.join([word for word in words if word not in list_stopwords])

tweets = tweets.apply(stopwords_removal)
tweets.head()

0    barusan liat tulisan di belakang truk rela inj...
1    her itu lho miss kevin sama keven rebutan gimb...
2       iya rep gatau saya masih kelas sd ehh di block
3       saya mohon tepatilah janjimu penantiancintaeps
4    bukan beria nk kahwin sbb gatal celah kangkang...
Name: Tweet, dtype: object

In [57]:
# Checking for null values
df.isna().sum()

sentimen    0
Tweet       0
dtype: int64

In [58]:
df['Tweet'] = tweets
df.head()

sentimen                                              Tweet
0       0.0  barusan liat tulisan di belakang truk rela inj...
1       0.0  her itu lho miss kevin sama keven rebutan gimb...
2       0.0     iya rep gatau saya masih kelas sd ehh di block
3       0.0     saya mohon tepatilah janjimu penantiancintaeps
4       0.0  bukan beria nk kahwin sbb gatal celah kangkang...

In [59]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

y = df["sentimen"]
#mengubah y menjadi integer
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = to_categorical(y)
print(y[0:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [60]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Tokenisasi
tokenizer = Tokenizer()
tokenizer.fit_on_texts(tweets)

In [61]:
word2vec=tokenizer.word_index
V=len(word2vec)
print('Dataset has %s number of independent tokens' %V)

Dataset has 23846 number of independent tokens


In [62]:
#fit_on_texts() menciptakan hubungan antara kata-kata dan bilangan-bilangan yg di-assign
#hubungan ini disimpan dalam dictionary dalam tokenizer.word_index
#kata-kata harus diganti dengan bilangan-bilangan yang di-assign
encoded_comments = tokenizer.texts_to_sequences(tweets)
print(encoded_comments[0:10])

[[1890, 145, 756, 7, 559, 1891, 1304, 6290, 6291, 493, 3, 30, 3642], [1159, 10, 697, 935, 3643, 34, 4606, 3644, 4607, 20, 1892, 1, 135, 1012, 463, 3645, 196, 4608, 2, 395, 147, 4609, 4610], [137, 629, 657, 1, 50, 582, 2085, 1230, 7, 1893], [1, 346, 6292, 3646, 3647], [43, 1894, 175, 630, 302, 1730, 3648, 9813, 16, 494, 87, 163, 5, 12, 677, 1, 23, 4611, 507, 164, 203, 6293], [1, 1052, 6294, 131, 1305, 1377, 11, 144, 4612, 2, 32, 1305, 208], [1, 154, 757, 134, 43, 9814, 9815, 77, 22, 72, 72, 9816, 82, 49, 158], [2, 1, 272, 3649, 27, 159, 2, 867, 2630, 1306, 482, 61, 117, 372, 16, 1053, 2308, 560, 243, 21], [3, 14, 8, 9817, 22, 1, 69], [2, 319, 13, 9818, 307, 27, 1, 111, 431, 2, 31, 1895]]


In [63]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
def get_sequences(tokenizer, tweets):
    sequences = tokenizer.texts_to_sequences(tweets)
    padded = pad_sequences(sequences, truncating = 'post', padding='post', maxlen=max_len)
    return padded
X = get_sequences(tokenizer, tweets)

In [64]:
print('Shape of X is ', X.shape)
print('Shape of y is', y.shape)

Shape of X is  (12308, 39)
Shape of y is (12308, 3)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y)

In [68]:
print(f'Bentuk X_train = {x_train.shape}',
      f'Bentuk Y_train = {y_train.shape}',
      f'Bentuk X_test = {x_test.shape}',
      f'Bentuk Y_test = {y_test.shape}', sep="\n")

Bentuk X_train = (9846, 39)
Bentuk Y_train = (9846, 3)
Bentuk X_test = (2462, 39)
Bentuk Y_test = (2462, 3)


In [ ]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255.0
x_test /= 255.0

array([[7.1647058e+00, 1.1764706e-02, 4.9411764e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [7.9019608e+00, 3.5941177e+01, 4.8117647e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.1529412e+00, 5.5294120e-01, 1.4133333e+01, ..., 6.3058825e+00,
        1.7294117e+00, 5.7411766e+00],
       ...,
       [1.5254902e+00, 6.7843137e+00, 8.6666667e-01, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.3647058e+00, 3.4901962e-01, 4.7058824e-02, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.9215689e-03, 1.2470589e+00, 2.3137255e-01, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [77]:
from tensorflow.keras.layers import Dense, Embedding,LSTM, Dropout, Bidirectional
from tensorflow.keras import Sequential
model = Sequential([
Embedding(10000,16,input_length=max_len),
Bidirectional(LSTM(20, return_sequences=True)),
Bidirectional(LSTM(20)),
Dense(3, activation='softmax')
])
model.compile(
     loss='categorical_crossentropy',
     optimizer='adam',
     metrics=['accuracy']
)

In [78]:
h = model.fit(
     x_train, y_train,
     validation_data=(x_test, y_test),
     epochs=20,
)

Epoch 1/20
308/308 [==============================] - 18s 38ms/step - loss: 0.7974 - accuracy: 0.6005 - val_loss: 0.6281 - val_accuracy: 0.6677
Epoch 2/20
308/308 [==============================] - 10s 32ms/step - loss: 0.4442 - accuracy: 0.7987 - val_loss: 0.4281 - val_accuracy: 0.8071
Epoch 3/20
308/308 [==============================] - 11s 34ms/step - loss: 0.4192 - accuracy: 0.8087 - val_loss: 0.4309 - val_accuracy: 0.8034
Epoch 4/20
308/308 [==============================] - 11s 36ms/step - loss: 0.4072 - accuracy: 0.8125 - val_loss: 0.4181 - val_accuracy: 0.8136
Epoch 5/20
308/308 [==============================] - 11s 37ms/step - loss: 0.4051 - accuracy: 0.8154 - val_loss: 0.4160 - val_accuracy: 0.8172
Epoch 6/20
308/308 [==============================] - 10s 34ms/step - loss: 0.4022 - accuracy: 0.8131 - val_loss: 0.4186 - val_accuracy: 0.8132
Epoch 7/20
308/308 [==============================] - 11s 34ms/step - loss: 0.3963 - accuracy: 0.8182 - val_loss: 0.4098 - val_accuracy:

In [79]:
model.save('model/sentimen_tweet.h5')